In [1]:
import numpy as np

# Создание массива из списка
Главной особенностью numpy является объект array, массивы схожи со списками, исключая тот момент, что
 все элементы массива должны иметь одинаковый тип

In [2]:
first_list = [1,2,3,4]

a = np.array(first_list, float)

In [3]:
a

array([1., 2., 3., 4.])

array принимает два аргумента: список для конвертации и тип для каждого элемента

In [4]:
type(a)

numpy.ndarray

манипулировать можно так же, как и обычными списками

In [5]:
a[:2]

array([1., 2.])

In [6]:
a[3]

4.0

In [7]:
a[3] = 5

In [8]:
a[3]

5.0

Массивы могут быть многомерными, можно задавать команды скобках
пример двумерного массива (матрицы)

In [9]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]], float)

In [10]:
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

Array slicing работает с многомерными массивами аналогично, как и с одномерными, применяя каждый срез, как фильтр для установленного измерения. Используйте ":" в измерении для указывания использования всех элементов этого измерения:

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a[1,:]

array([4., 5., 6.])

In [12]:
a[:,2]

array([3., 6.])

In [13]:
a[-1:, -2:]

array([[5., 6.]])

Метод shape возвращает количество строк и столбцов в матрице:

In [15]:
a.shape

(2, 3)

Метод dtype возвращает тип переменных, хранящихся в массиве:

In [16]:
a.dtype

dtype('float64')

Тут float64, это числовой тип данных в numpy, который используется для хранения вещественных чисел двойной точности. Так как же float в Python.

Метод len возвращает длину первого измерения (оси):


In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)

In [18]:
len(a)

2

Метод in используется для проверки на наличие элемента в массиве:

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)

In [20]:
2 in a

True

In [21]:
100 in a

False

Массивы можно переформировать при помощи метода, который задает новый многомерный массив. Следуя следующему примеру, мы переформатируем одномерный массив из десяти элементов во двумерный массив, состоящий из пяти строк и двух столбцов:

In [22]:
a = np.array(range(10), float)

In [23]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
a = a.reshape((5, 2))

In [25]:
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [26]:
a.shape

(5, 2)

Метод reshape создает новый массив, а не модифицирует оригинальный.

Имейте ввиду, связывание имен в python работает и с массивами. Метод copy используется для создания копии существующего массива в памяти:

In [27]:
a = np.array([1, 2, 3], float)

In [28]:
b = a

In [29]:
c = a.copy()

In [30]:
a[0] = 0

In [31]:
a

array([0., 2., 3.])

In [32]:
b

array([0., 2., 3.])

In [33]:
c

array([1., 2., 3.])

Списки можно тоже создавать с массивов

In [34]:
a = np.array([1, 2, 3], float)

In [35]:
a.tolist()

[1.0, 2.0, 3.0]

In [36]:
list(a)

[1.0, 2.0, 3.0]

Можно также переконвертировать массив в бинарную строку (то есть, не human-readable форму). Используйте метод tostring для этого. Метод fromstring работает в для обратного преобразования. Эти операции иногда полезны для сохранения большого количества данных в файлах, которые могут быть считаны в будущем.

In [38]:
a = np.array([1, 2, 3], float)

In [39]:
s = a.tostring()

In [40]:
s

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [42]:
np.fromstring(s)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([1., 2., 3.])

In [43]:
np.frombuffer(s)

array([1., 2., 3.])

Заполнение массива одинаковым значением.

In [45]:
a = np.array([1, 2, 3], float)

In [46]:
a

array([1., 2., 3.])

In [48]:
a.fill(0)

In [49]:
a

array([0., 0., 0.])

Транспонирование массивов также возможно, при этом создается новый массив:

In [50]:
a = np.array(range(6), float).reshape((2, 3))

In [51]:
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [52]:
a.transpose()

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

Многомерный массив можно переконвертировать в одномерный при помощи метода flatten:

In [53]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)

In [54]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [55]:
a.flatten()

array([1., 2., 3., 4., 5., 6.])

Два или больше массивов можно сконкатенировать при помощи метода concatenate:

In [56]:
a = np.array([1,2], float)

In [57]:
b = np.array([3,4,5,6], float)

In [58]:
c = np.array([7,8,9], float)

In [59]:
np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

Если массив не одномерный, можно задать ось, по которой будет происходить соединение. По умолчанию (не задавая значения оси), соединение будет происходить по первому измерению:

In [60]:
a = np.array([[1, 2], [3, 4]], float)

In [61]:
b = np.array([[5, 6], [7,8]], float)

In [63]:
np.concatenate((a,b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [64]:
np.concatenate((a,b), axis = 0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [65]:
np.concatenate((a,b), axis = 1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

В заключении, размерность массива может быть увеличена при использовании константы newaxis в квадратных скобках:

In [66]:
a = np.array([1, 2, 3], float)

In [67]:
a

array([1., 2., 3.])

In [68]:
a[:,np.newaxis]

array([[1.],
       [2.],
       [3.]])

In [69]:
a[:,np.newaxis].shape

(3, 1)

In [70]:
b[np.newaxis,:]

array([[[5., 6.],
        [7., 8.]]])

In [71]:
b[np.newaxis,:].shape

(1, 2, 2)

Заметьте, тут каждый массив двумерный; созданный при помощи newaxis имеет размерность один. 
Метод newaxis подходит для удобного создания надлежаще-мерных массивов в векторной и матричной математике.