# Другие пути создания массивов

In [2]:
import numpy as np

Функция arange аналогична функции range, но возвращает массив

In [4]:
np.arange(5, dtype = float)


array([0., 1., 2., 3., 4.])

In [5]:
np.arange(1,6,2, dtype = int)

array([1, 3, 5])

Функции zeros и ones создают новые массивы с установленной размерностью, заполненные этими значениями

In [7]:
np.ones((2,3),dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.zeros((5,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Функции zeros_like и ones_like могут преобразовать уже созданный массив нулями и единицами соотвественно

In [15]:
a = np.array([[1,2,3], [3,4,5]],float)
print(a)

[[1. 2. 3.]
 [3. 4. 5.]]


In [16]:
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

Также есть некоторое количество функций для создания специальных матриц. Для создания квадратной матрицы с главной диагональю, которая заполняется единицами, воспользуемся методов identity

In [19]:
np.identity(4, dtype = float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Функция eye создает квадратную матрицу с единичками на k-й диагонали

In [23]:
np.eye(4, k=0, dtype = float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Математические операции над массивами

Когда для массивов мы используем стандартные математические операции, должен соблюдаться принципе элемент - элемент. Это означает,
что массивы должны быть одинакового размера во время сложения, вычитания и тому подобных операций:

In [27]:
a = np.array([1,2,3], float)
b = np.array([4,5,6], float)
a + b

array([5., 7., 9.])

In [29]:
a - b

array([-3., -3., -3.])

In [30]:
a * b

array([ 4., 10., 18.])

In [31]:
b/a

array([4. , 2.5, 2. ])

In [32]:
a % b

array([1., 2., 3.])

In [33]:
a ** b

array([  1.,  32., 729.])

In [34]:
b ** a

array([  4.,  25., 216.])