# Операторы сравнения и тестирования значений

Булево сравнение может быть использовано для поэлементного сравнения массивов одинаковых длин, возвращаемое значение - это
массив булевых значений True/False

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3], float)
b = np.array([0, 2 ,3], float)
a>b

array([ True, False, False])

In [4]:
a == b

array([False,  True,  True])

In [5]:
a <= b

array([False,  True,  True])

Результат сравнения может быть сохранен в массива

In [9]:
c = a>b

In [10]:
c

array([ True, False, False])

Массивы могут сравнены быть с одиночным значением

In [11]:
a = np.array([1,3,0], float)
a > 2

array([False,  True, False])

Операторы  any и all могут быть использованы для определения истинны ли хотя бы один или все элементы соответственно

In [12]:
с = np.array([True, False, True], bool)
any(c)


False

In [13]:
all(c)

False

Комбинированные булевы выражения могут быть применены к массивам по принципу элемент - элемент, используя специальные функции logical_and, logical_or, logical_not

In [14]:
a = np.array([1, 3, 0], float)
np.logical_and(a>0, a<3)

array([ True, False, False])

In [15]:
b = np.array([True, False, False], bool)
np.logical_not(b)

array([False,  True,  True])

In [16]:
c = np.array([False, True, False], bool)
np.logical_or(b,c)

array([ True,  True, False])

Функция where создает новый массив из двух других массивов одинаковой длины используя булев фильтр для выбора между двумя элементами.
Базовый синтаксис where(boolarray, truearray, falsearray)

In [19]:
a = np.array([1, 3, 1], float)
np.where(a != 0, 1 / a, a)

array([1.        , 0.33333333, 1.        ])

С функцией where может быть реализовано также массовое сравнение

In [20]:
np.where(a>0, 3, 2)

array([3, 3, 3])

Некоторые функции дают возможность тестировать значения в массиве. Функция nonzero возвращает кортеж индексов ненулевых значений.
Количество элементов в кортеже равно количеству осей в массиве

In [22]:
a = np.array([[0,1],[3,0]], float)
a.nonzero()

(array([0, 1]), array([1, 0]))

Также можно проверить значения на конечность и NaN (Not a Number)

In [23]:
a = np.array([1, np.NaN, np.Inf], float)

In [24]:
a

array([ 1., nan, inf])

In [25]:
np.isnan(a)

array([False,  True, False])

In [28]:
np.isinf(a)

array([False, False,  True])

Хотя здесь мы использовали константы numpy, чтобы добавить значения NaN и бесконечность, они могут быть результатом применения
стандартных математических операций

# Выбор элементов массива и манипуляция с ними

Мы уже видели, как и у списков, элементы массива можно получить используя операцию доступа по индексу. Однако, в отличие от списков,
массивы также позволяют делать выбор элементов, используя другие массивы. Это значит, что мы можем использовать массив для фильтрации специфических подмножеств других массивов.

 Булевы массивы могут быть использованы как массивы для филтрации

In [29]:
a = np.array([[6,4], [5,9]], float)
a >= 5

array([[ True, False],
       [ True,  True]])

In [30]:
a [a>=6]

array([6., 9.])

Стоит заметить, что когда мы передаем булев массив a >= 6, как индекс для операции доступа по индексу массива a, возвращаемый массив будет
хранить только True-значения. Также мы можем записать массив для фильтрации в переменную

In [31]:
a = np.array([[6,4],[5,9]], float)
sel = (a >= 6)
a[sel]

array([6., 9.])

Более замысловатая филтьтрация может быть достигнуты использование булевых выражений

In [33]:
a[np.logical_and(a>5, a<9)]

array([6.])

В придачу к булеву выбору, также можно использовать целочисленные массивы. В этом случае целочисленный массивы хранит индексы элементов, которые буду взяты из массива, рассмотрим следующий одномерный пример:

In [36]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

array([2., 2., 4., 8., 6., 4.])

Иными словами когда мы используем b для получения эелементов из a, мы берем нулевой, нулевой, первый, третий, второй, первый эелементы первого массива. Списки могут быть так же использованы, как массивы для фильтрации:

In [39]:
a = np.array([2,4,6,8], float)
a[[0, 0, 1, 3, 2, 1]]

array([2., 2., 4., 8., 6., 4.])

Для многомерных массивов нам необходимо передать несколько одномерных целочисленных массивов в оператор доступа по индексу для каждой оси, потом каждый из массивов проходит такую последовательность: первый элемент соответствует индексу строки, который является первым элементом массива b, второй элемент соответствует индексу столбца, который является первым элементов массива c и так далее. Пример:

In [40]:
a = np.array([[1,4],[9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1],int)
a[b, c]

array([ 1.,  4., 16., 16.,  4.])

In [41]:
a

array([[ 1.,  4.],
       [ 9., 16.]])

Специальная функция take доступна для выполнения выборки с целочисленными массивами, это работает так же, как и использование оператора взятия по индексу

In [43]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int)
a.take(b)

array([2., 2., 4., 8., 6., 4.])

Функция take также предоставляет аргумент axis(ось) для взятия подсекции многомерного массива вдоль какой-либо оси

In [45]:
a = np.array([[0,1], [2,3]],float)
b = np.array([0,0,1], int)
a.take(b,axis=1)

array([[0., 0., 1.],
       [2., 2., 3.]])

В противоположность функции take есть функция put, которая будет брать значения из исходного массива и записывать их на специфические индексы в другом put-массиве 

In [46]:
a = np.array([0,1,2,3,4,5], float)
b = np.array([9,8,7], float)
a.put([0,3], b)

In [47]:
a

array([9., 1., 2., 8., 4., 5.])

Заметим, что значение 7 из исходного массива b не было использовано, так как только 2 индекса [0,3] указаны. Исходный массив будет повторен в случае несоответствия длин

In [48]:
a = np.array([0,1,2,3,4,5], float)
a.put([0,3],5)

In [49]:
a

array([5., 1., 2., 5., 4., 5.])

# Векторная и матричная математика

NumPy обеспечивает много функций для работы с векторами и матрицами. Функция dot возвращает скалярное произведение векторов

In [3]:
a = np.array([1,2,3], float)
b = np.array([0,1,1], float)
np.dot(a,b)

5.0

Функция dot может также умножать матрицы

In [5]:
a = np.array([[0,1],[2,3]],float)
b = np.array([2,3], float)
c = np.array([[1,1], [4,0]], float)
a

array([[0., 1.],
       [2., 3.]])

In [6]:
np.dot(b,a)

array([ 6., 11.])

In [7]:
np.dot(a,b)

array([ 3., 13.])

In [8]:
np.dot(a,c)

array([[ 4.,  0.],
       [14.,  2.]])

In [9]:
np.dot(c,a)

array([[2., 4.],
       [0., 4.]])

Также можно получить скалярное, тензорное и внешнее произведение матриц и векторов. Заметим, что для векторов внутреннее и скалярное произведение совпадает

In [11]:
a = np.array([1,4,0], float)
b = np.array([2,2,1],float)
np.outer(a,b)

array([[2., 2., 1.],
       [8., 8., 4.],
       [0., 0., 0.]])

In [12]:
np.inner(a,b)

10.0

In [13]:
np.cross(a,b)

array([ 4., -1., -6.])

NumPy также предоставляет набор встроенных функций и методов для работы с линейной алгеброй. Это все можно найти в подмодуле linalg. Этими модулями также можно оперировать с вырожденными и невырожденными матрицами. Определитель матрицы ищется таким образом:

In [14]:
a = np.array([[4,2,0], [9,3,7], [1,2,1]], float)
a

array([[4., 2., 0.],
       [9., 3., 7.],
       [1., 2., 1.]])

In [15]:
np.linalg.det(a)

-48.00000000000003

Также можно найти собственный вектор и собственное значение матрицы

In [16]:
vals, vecs = np.linalg.eig(a)

In [17]:
vals

array([ 8.85591316,  1.9391628 , -2.79507597])

In [18]:
vecs

array([[-0.3663565 , -0.54736745,  0.25928158],
       [-0.88949768,  0.5640176 , -0.88091903],
       [-0.27308752,  0.61828231,  0.39592263]])

Невырожденная матрица может быть найдена так

In [19]:
b = np.linalg.inv(a)

In [20]:
b

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [21]:
np.dot(a,b)

array([[ 1.00000000e+00,  0.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00, -2.77555756e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

Одиночное разложение(аналог диагонализации неквадратной матрицы) может быть достигнут так:

In [22]:
a = np.array([[1,3,4], [5,2,3]],float)

In [24]:
U, s, Vh = np.linalg.svd(a)

In [25]:
U

array([[-0.6113829 , -0.79133492],
       [-0.79133492,  0.6113829 ]])

In [26]:
s

array([7.46791327, 2.86884495])

In [27]:
Vh

array([[-0.61169129, -0.45753324, -0.64536587],
       [ 0.78971838, -0.40129005, -0.46401635],
       [-0.046676  , -0.79349205,  0.60678804]])