# Другие пути создания массивов

In [2]:
import numpy as np

Функция arange аналогична функции range, но возвращает массив

In [4]:
np.arange(5, dtype = float)


array([0., 1., 2., 3., 4.])

In [5]:
np.arange(1,6,2, dtype = int)

array([1, 3, 5])

Функции zeros и ones создают новые массивы с установленной размерностью, заполненные этими значениями

In [7]:
np.ones((2,3),dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.zeros((5,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Функции zeros_like и ones_like могут преобразовать уже созданный массив нулями и единицами соотвественно

In [15]:
a = np.array([[1,2,3], [3,4,5]],float)
print(a)

[[1. 2. 3.]
 [3. 4. 5.]]


In [16]:
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

Также есть некоторое количество функций для создания специальных матриц. Для создания квадратной матрицы с главной диагональю, которая заполняется единицами, воспользуемся методов identity

In [19]:
np.identity(4, dtype = float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Функция eye создает квадратную матрицу с единичками на k-й диагонали

In [23]:
np.eye(4, k=0, dtype = float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Математические операции над массивами

Когда для массивов мы используем стандартные математические операции, должен соблюдаться принципе элемент - элемент. Это означает,
что массивы должны быть одинакового размера во время сложения, вычитания и тому подобных операций:

In [27]:
a = np.array([1,2,3], float)
b = np.array([4,5,6], float)
a + b

array([5., 7., 9.])

In [29]:
a - b

array([-3., -3., -3.])

In [30]:
a * b

array([ 4., 10., 18.])

In [31]:
b/a

array([4. , 2.5, 2. ])

In [32]:
a % b

array([1., 2., 3.])

In [33]:
a ** b

array([  1.,  32., 729.])

In [34]:
b ** a

array([  4.,  25., 216.])

Для двухмерных массивов умножение остается поэлементным и не соответствует умножению матриц

In [5]:
a = np.array([[1,2,3], [3,4,5]], float)
b = np.array([[3,2,1], [5,4,3]], float)

c = a * b
print(c)

[[ 3.  4.  3.]
 [15. 16. 15.]]


При несоответствии размеров массивов выбрасывается ошибка

In [9]:
a = np.array([1,2,3], float)
b = np.array([4,5], float)
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

Однако, если размерность массивов не совпадает, они будут преобразованы для выполнения математических операций. Это зачастую означает,
что меньший массив будет испльзован несколько раз для завершения операций

In [12]:
a = np.array([[1,2], [3,4], [5,6]],float)
b = np.array([-1,3], float)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [13]:
b

array([-1.,  3.])

In [14]:
a + b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

Тут одномерный массив b был преобразован в двухмерный, который соответствует размеру массива a, по существу массив b был повторен
несколько раза для каждой строки, иначе его можно представить так

In [16]:
a = np.array([[-1,3], [-1,3], [-1,3]],float)
a

array([[-1.,  3.],
       [-1.,  3.],
       [-1.,  3.]])

Python автоматически преобразовывает массивы в этом случае. Иногда, когда преобразование играет роль, мы можем использовать константу newaxis, чтобы изменить преобразование

In [18]:
a = np.zeros((2,2), float)
b = np.array([-1,3], float)
a

array([[0., 0.],
       [0., 0.]])

In [20]:
b

array([-1.,  3.])

In [21]:
a + b

array([[-1.,  3.],
       [-1.,  3.]])

In [23]:
a + b[:, np.newaxis]

array([[-1., -1.],
       [ 3.,  3.]])

In [24]:
a + b [np.newaxis,:]

array([[-1.,  3.],
       [-1.,  3.]])

Вдобавок к стандартным операторам, в numpy включена библиотека стандартных математических функций, которые могут быть поэлементно применены к массивам. Собственно функции: abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, и arctanh.

In [26]:
a = np.array([1.1, 1.5, 1.9], float)
np.sqrt(a)

array([1.04880885, 1.22474487, 1.37840488])

In [27]:
a = np.array([1.1, 1.5, 1.9], float)
np.floor(a)

array([1., 1., 1.])

In [28]:
np.ceil(a)

array([2., 2., 2.])

In [29]:
np.rint(a)

array([1., 2., 2.])

In [30]:
np.pi

3.141592653589793

In [31]:
np.e

2.718281828459045

# Перебор элементов массива

Проводить итерацию массивов можно аналогично спискам

In [33]:
a = np.array([1,3,5], float)
for i in a:
    print(i)

1.0
3.0
5.0


Для многомерных массивов итерация будет проводиться по первой оси, так, что каждый проход цикла будет возвращать строку массива

In [34]:
a = np.array([[1,2], [3,4], [5,6]], float)
for i in a:
    print(i)

[1. 2.]
[3. 4.]
[5. 6.]


Множественное присваивание также доступно при итерации

In [4]:
a = np.array([[1,2], [3,4], [5,6]], float)
for (x,y) in a:
    print(x * y)

2.0
12.0
30.0


# Базовые операции над массивами

Для получения каких-либо свойств массивов существует много функций. Элементы могут быть суммированы или перемножены

In [6]:
a = np.array([2,3,4],float)
a.sum()

9.0

In [7]:
a.prod()

24.0

В этом примере были использованы функции массива. Также можно использовать собственные функции numpy

In [8]:
np.sum(a)

9.0

In [9]:
np.prod(a)

24.0

Для большинства случаев могут использоваться оба варианта.
Некие функции дают возморжность оперировать статистическими данными. Это функции mean(среднее арифметические), вариация и девиация:

In [12]:
a = np.array([2,1,9], float)
a.mean()

4.0

In [13]:
a.var()

12.666666666666666

In [14]:
a.std()

3.559026084010437

Можно найти максимум и минимум в массиве

In [15]:
a = np.array([1,2,3,4,5,9],float)
a.max()

9.0

In [16]:
a.min()

1.0

Функции argmin и argmax возвращают индексы минимального и максимального элементов

In [18]:
a = np.array([1,2,2,7,5,6,78],float)
a.argmin()

0

In [19]:
a.argmax()

6

Для многомерных массивов каждая из функций может принять доволнительный аргумент axis
и в зависимости от его значения выполнять функции по определенной оси, помещая результаты исполнения в массив

In [20]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]],float)

In [23]:
a.mean(axis = 0)

array([4., 5., 6.])

In [24]:
a.mean(axis = 1)

array([4., 5., 6.])

In [26]:
a.max(axis = 0)

array([7., 8., 9.])

In [27]:
a.min(axis = 0)

array([1., 2., 3.])

Как и списки, массивы можно сортировать

In [28]:
a = np.array([1,3,4,2,-1,3,4,5,-9], float)

In [29]:
sorted(a)

[-9.0, -1.0, 1.0, 2.0, 3.0, 3.0, 4.0, 4.0, 5.0]

In [30]:
a.sort()

In [31]:
a

array([-9., -1.,  1.,  2.,  3.,  3.,  4.,  4.,  5.])

Значения в массиве могут быть сокращены, чтобы принадлежать диапазону. Это то же самое, что применять min(max(x,minval), maxval)
к каждому элементу x:

In [32]:
a = np.array([6,4,4,5,4,3,6,86,], float)

In [34]:
a.clip(0,6)

array([6., 4., 4., 5., 4., 3., 6., 6.])

Уникальные элементы могут быть извлечены вот так:

In [37]:
a = np.array([[1,1,3,3,5,5],[2,2,4,4,6,6]], float)

In [38]:
np.unique(a)

array([1., 2., 3., 4., 5., 6.])

Для двухмерных массивов диагональ можно получит вот так:

In [39]:
a = np.array([[1,2], [3,4], [5,6]], float)

In [40]:
a.diagonal()

array([1., 4.])