# Математика многочленов

NumPy предоставляет методы работы с полиномами. Передавая список корней, можно получить коэффициенты уравнения

In [1]:
import numpy as np

In [2]:
np.poly([-1, 1, 1, 10])

array([  1., -11.,   9.,  11., -10.])

Здесь массив возвращает коэффициенты, соответсвующие уравнению x^4 - 11x^3 + 9x^2 + 11x - 10
Может быть произведена обратная операция, передавая все коэффиценты, функция root, вернет все корни многочлена

In [3]:
np.roots([1, 4, -2, 3])

array([-4.5797401 +0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

Заметим, что в уравнении x^3 + 4x^2 - 2x + 3 два корня мнимые.
Коэффициенты многочлена могут быть интегрированы. Рассмотрим интегрирование x^3 + x^2 + x + 1 в x^4/4 + x^3/3 + x^2/2 + x + C
Обычно константа C равна нулю

In [4]:
np.polyint([1, 1, 1, 1])

array([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

Аналогично могут быть взяты производные

In [6]:
np.polyder([1.0/4.0, 1.0/3.0, 1.0/2.0, 1.0, 0])

array([1., 1., 1., 1.])

Функции polyadd, polysub, polymul, polydiv также поддерживают суммирование суммирование, вычитание, умножение и деление коэффициентов многочлена соответственно
Функция polyval подставляет в многолчен заданное значение. Рассмотрим многочлен x^3 - 2x^2 + 2 при  x = 4

In [7]:
np.polyval([1, -2, 0, 2], 4)

34

В завключение, функция polyfit может быть использована для подбора(интерполяции) многочлена заданного порядка к набору значений

In [9]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [0, 2, 1, 3, 7, 10, 11, 19]
np.polyfit(x, y, 2)

array([ 0.375     , -0.88690476,  1.05357143])

Возвращаемый массив есть коэффициенты многочлены, более утонченная интерполяция может быть найдена в scipy

# Статистика

В придачу к функциям mean, var и std, NumPy предоставляет еще некоторые данные для работы со статистичечскими данными в массивах.
Медиана может быть найдена так:

In [11]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float)
np.median(a)

3.0

Коэффициент корреляции для некоторых переменных наблюдается несколько раз и может быть найден из массивов вида: 
[[x1, x2, ...], [y1, y2, ...], [z1, z2, ...], ...], где x, y, z это разные квантовые наблюдаемые и номера указывают на количество их "наблюдений": 

In [13]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)
c = np.corrcoef(a)

In [14]:
c

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

Имеем возвращаемый массив c[i, j], который хранит корреляционный коэффициент для i-х и j-х квантовыхнаблюдаемых.
Аналогично, ковариационный момент может быть найден:

In [15]:
np.cov(a)

array([[0.91666667, 2.08333333],
       [2.08333333, 8.91666667]])

# Случайные числа

Важная часть каждой симуляции - это возможность генерировать случайные числа. Для этого мы используемый встроенный в NumPy генератор псевдослучайных чисел в подмодуле random. Числа являются псевдослучайны, потому что они сгенерированы детерминически из порождающего элемента (seed number), но рассредоточены в статистическом сходстве  с случайным образом. Для генерации NumPy использует особенный алгоритм Mersenne Twister. Задать порождающий элемент можно так:

In [16]:
np.random.seed(293423)

seed - это целое число. Каждая программа, которая запускается с одинаковым seed, будет генерировать одинаковую последовательность чисел каждый раз. Это может быть полезно для отладки, но вообще нам не нужно задавать seed, на самом деле когда мы запускаем программу несколько раз, мы хотим каждый раз получать разную последовательность чисел. Если эта команда не будет выполнена, NumPy автоматически выбирает случайный seed(Базирующийся на времени), который является разным при каждом запуске программы.
Массив случайных чисел из интервала [0.0, 1.0] может быть сгенерирован следующим образом

In [17]:
np.random.rand(5)

array([0.33677247, 0.52693437, 0.79529578, 0.78867702, 0.02147624])

Функция rand может быть использована для генерации двумерных массивов, или можно использовать функцию reshape:

In [18]:
np.random.rand(2,3)

array([[0.84612516, 0.0704939 , 0.1526965 ],
       [0.77831701, 0.80821151, 0.82198398]])

In [20]:
np.random.rand(6).reshape((2,3))

array([[0.43767263, 0.15292493, 0.20882971],
       [0.306344  , 0.45719255, 0.60260853]])

Для генерации случайно числа на интервале [0.0, 1.0]:

In [21]:
np.random.random()

0.2006834957335677

Для генерации случайного числа в диапазоне [min, max]:

In [22]:
np.random.randint(5, 10)

6